name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release Package
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: "npm"

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run Semantic Release
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub token for the release
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }} # NPM token to publish the package
        run: npx semantic-release
